eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8021
spring:
  application:
    name: order-service-feign-hystrix
feign:
  hystrix:
    enabled: true